USE `EmployeeDB`;

alter table DEPENDENT
  add CONSTRAINT `fk_DEPENDENT_EMPLOYEE1`
   FOREIGN KEY (`ESSN`)
   REFERENCES `EmployeeDB`.`EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
   ON UPDATE NO ACTION;
alter table WORKS_ON
  add CONSTRAINT `fk_EMPLOYEE_has_PROJECT_EMPLOYEE1`
    FOREIGN KEY (`ESSN`)
    REFERENCES `EmployeeDB`.`EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table WORKS_ON
  add CONSTRAINT `fk_EMPLOYEE_has_PROJECT_PROJECT1`
    FOREIGN KEY (`PNumber`)
    REFERENCES `EmployeeDB`.`PROJECT` (`PNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table DEPT_LOCATION  
 add CONSTRAINT `fk_DEPT_LOCATION_DEPARTMENT1`
    FOREIGN KEY (`DNumber`)
    REFERENCES `EmployeeDB`.`DEPARTMENT` (`DNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table EMPLOYEE  
  add CONSTRAINT `fk_EMPLOYEE_DEPARTMENT`
   FOREIGN KEY (`DNumber`)
    REFERENCES `EmployeeDB`.`DEPARTMENT` (`DNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table EMPLOYEE   
  add CONSTRAINT `fk_EMPLOYEE_EMPLOYEE1`
    FOREIGN KEY (`SupervisorSSN`)
    REFERENCES `EmployeeDB`.`EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table DEPARTMENT 
  add CONSTRAINT `fk_DEPARTMENT_EMPLOYEE1`
   FOREIGN KEY (`MgrSSN`)
    REFERENCES `EmployeeDB`.`EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table PROJECT
  add CONSTRAINT `fk_PROJECT_DEPARTMENT1`
   FOREIGN KEY (`DNumber`)
    REFERENCES `EmployeeDB`.`DEPARTMENT` (`DNumber`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION;
